# fly.toml app configuration file generated for djsite on 2023-07-02T10:53:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "djsite"
primary_region = "ams"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
