# Generated by Django 4.2.2 on 2023-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_about_social_imageabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageabout',
            name='alt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
