# Generated by Django 4.2.2 on 2023-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_imageabout_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageabout',
            name='alt',
            field=models.CharField(max_length=100),
        ),
    ]
