# Generated by Django 4.2.2 on 2023-07-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_imageabout_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='image',
            new_name='icon',
        ),
    ]
