# Generated by Django 4.2.2 on 2023-07-02 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 17, 23, 54, 64134, tzinfo=datetime.timezone.utc)),
        ),
    ]
