# Generated by Django 4.2.2 on 2023-07-02 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 17, 24, 22, 740069, tzinfo=datetime.timezone.utc)),
        ),
    ]
