# Generated by Django 4.2.2 on 2023-07-08 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_comment_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 8, 12, 49, 943577, tzinfo=datetime.timezone.utc)),
        ),
    ]
