# Generated by Django 4.2.2 on 2023-07-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
